EduManSys:EducationManagementSys.cpp mysql_op.cpp 
	g++ -o $@ $^ -I /home/xuhuan/git/Project/Http/Http_Multithread/cgiOperation/mysql/include -L /home/xuhuan/git/Project/Http/Http_Multithread/cgiOperation/mysql/lib -lmysqlclient
.PHONY:clean
clean:
	rm -f EduManSys

.PHONY:output
output:
	cp EduManSys ..
